version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-java-spring

    docker:
      - image: circleci/openjdk:11-stretch

    steps:
      - checkout

      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run: ./gradlew clean --refresh-dependencies build -Dimage=gssdockertest/circle-ci-demo-doc-image:$CIRCLE_BUILD_NUM

      - store_artifacts:
          path: build/libs/CiCd-0.0.1-SNAPSHOT.jar

#      - aws-ecr/build-and-push-image:
#          repo: slackcicd
#          tag: "latest,v0.1.${CIRCLE_BUILD_NUM}"
#          dockerfile: build/Dockerfile.prod
#          path: .
#          requires:
#            - test