version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-java-spring

    docker:
      - image: circleci/openjdk:11-stretch

    steps:
      - checkout

      - run: ./gradlew clean --refresh-dependencies build

      - store_artifacts:
          path: build/libs/CiCd-0.0.1-SNAPSHOT.jar